"""
Crisis Detection Keywords Module
================================
CRITICAL SAFETY CODE for MindMate AI

This module contains comprehensive keyword and phrase lists for detecting
mental health crises including suicidal ideation, self-harm, and hopelessness.

WARNING: This is life-safety critical code. All keywords have been reviewed
by mental health professionals. Modifications require clinical oversight.

Classification:
- CRITICAL: Immediate intervention required
- HIGH: Urgent attention needed
- MODERATE: Elevated concern
- LOW: Monitor and track
"""

from dataclasses import dataclass
from typing import List, Dict, Set, Tuple
import re
from enum import Enum


class KeywordSeverity(Enum):
    """Severity levels for keyword classification."""
    CRITICAL = "critical"
    HIGH = "high"
    MODERATE = "moderate"
    LOW = "low"


@dataclass
class KeywordMatch:
    """Result of a keyword match."""
    keyword: str
    severity: KeywordSeverity
    category: str
    position: int
    context: str  # Surrounding text for review


class CrisisKeywords:
    """
    Comprehensive crisis detection keyword database.
    
    Keywords are organized by category and severity level.
    Each keyword includes context-aware matching patterns.
    """
    
    # =========================================================================
    # CRITICAL - IMMEDIATE INTERVENTION REQUIRED
    # =========================================================================
    
    SUICIDAL_CRITICAL: List[str] = [
        # Direct statements of intent
        "i'm going to kill myself",
        "i am going to kill myself",
        "im going to kill myself",
        "i will kill myself",
        "i'm killing myself",
        "i am killing myself",
        "i'm going to end my life",
        "i am going to end my life",
        "i will end my life",
        "i'm ending my life",
        "i'm going to commit suicide",
        "i am going to commit suicide",
        "i will commit suicide",
        "i'm committing suicide",
        "i have decided to kill myself",
        "i've decided to kill myself",
        "i have a plan to kill myself",
        "i have a plan to end my life",
        "i know how i'm going to do it",
        "i know exactly how i'm going to do it",
        "i've planned it all out",
        "i have everything ready",
        "i have the pills",
        "i have a gun",
        "i have a rope",
        "i bought a gun",
        "i bought pills",
        "i'm going to do it tonight",
        "i'm doing it tonight",
        "tonight is the night",
        "this is my last day",
        "i won't be here tomorrow",
        "you won't see me again",
        "say goodbye",
        "i'm saying goodbye",
        "i want to die",
        "i just want to die",
        "i wish i was dead",
        "i wish i were dead",
        "i'd be better off dead",
        "everyone would be better off if i was dead",
        "the world would be better without me",
        "no one would miss me",
        "i'm a burden",
        "i'm just a burden",
        "i'm worthless",
        "i have no reason to live",
        "i don't want to live anymore",
        "i can't do this anymore",
        "i give up",
        "i've given up",
        "i quit",
        "i'm done",
        "i'm finished",
        "it's over for me",
        "there's no point anymore",
        "nothing matters anymore",
        "i don't care what happens to me",
        "i hope i don't wake up",
        "i hope i die in my sleep",
        "i want to go to sleep and never wake up",
        "i want to disappear",
        "i wish i could disappear",
        "i wish i'd never been born",
        "i regret being born",
        "life is not worth living",
        "living is too painful",
        "i can't take the pain anymore",
        "the pain is too much",
        "i'm in constant pain",
        "there's no way out",
        "there's no escape",
        "i see no way out",
        "i'm trapped",
        "i feel trapped",
        "i can't escape",
        "i want the pain to stop",
        "i need the pain to stop",
        "make it stop",
        "please make it stop",
        "i can't go on",
        "i can't continue",
        "i don't see a future",
        "i have no future",
        "my future is over",
        "i've ruined everything",
        "i've destroyed my life",
        "i've lost everything",
        "i have nothing left",
        "i am nothing",
        "i feel empty inside",
        "i'm hollow",
        "i'm numb",
        "i feel dead inside",
        "i'm already dead inside",
        "i'm a ghost",
        "i don't feel real",
        "nothing feels real",
        "i'm disconnected from everything",
        "i don't belong here",
        "i don't fit in this world",
        "i'm a mistake",
        "my existence is a mistake",
        "i shouldn't exist",
        "i shouldn't be here",
        "i've made up my mind",
        "i'm set on this",
        "nothing will change my mind",
        "it's too late for me",
        "it's hopeless",
        "i'm hopeless",
        "there's no hope for me",
        "i've lost all hope",
        "hope is gone",
    ]
    
    SELF_HARM_CRITICAL: List[str] = [
        # Direct self-harm statements
        "i'm going to cut myself",
        "i am going to cut myself",
        "im going to cut myself",
        "i will cut myself",
        "i'm cutting myself",
        "i cut myself",
        "i just cut myself",
        "i'm cutting right now",
        "i have my blade",
        "i have my razor",
        "i have a knife",
        "i'm bleeding",
        "i'm bleeding right now",
        "i can't stop bleeding",
        "i took too many pills",
        "i overdosed",
        "i'm overdosing",
        "i took a lot of pills",
        "i swallowed pills",
        "i'm going to overdose",
        "i want to overdose",
        "i'm burning myself",
        "i burn myself",
        "i'm hitting myself",
        "i hit myself",
        "i'm hurting myself",
        "i hurt myself",
        "i'm harming myself",
        "i harm myself",
        "i'm punishing myself",
        "i deserve pain",
        "i deserve to suffer",
        "i deserve to be hurt",
        "i want to feel pain",
        "pain makes me feel alive",
        "i need to feel something",
        "i need to punish myself",
        "i'm scratching myself",
        "i scratch myself",
        "i'm pulling my hair",
        "i pull my hair",
        "i'm banging my head",
        "i bang my head",
        "i'm starving myself",
        "i starve myself",
        "i don't eat on purpose",
        "i'm making myself throw up",
        "i make myself throw up",
        "i'm purging",
        "i purge",
    ]
    
    # =========================================================================
    # HIGH SEVERITY - URGENT ATTENTION NEEDED
    # =========================================================================
    
    SUICIDAL_HIGH: List[str] = [
        # Strong indicators requiring prompt response
        "i think about killing myself",
        "i think about suicide",
        "i've thought about killing myself",
        "i've been thinking about suicide",
        "suicide thoughts",
        "suicidal thoughts",
        "i'm having suicidal thoughts",
        "i have suicidal thoughts",
        "i've been suicidal",
        "i feel suicidal",
        "i'm feeling suicidal",
        "i want to kill myself",
        "i want to end my life",
        "i want to commit suicide",
        "i'm considering suicide",
        "i've considered suicide",
        "i'm thinking about ending it all",
        "i've thought about ending it all",
        "ending it all",
        "end it all",
        "i want to end it all",
        "i'm planning to kill myself",
        "i've been planning",
        "i have a plan",
        "i'm making a plan",
        "i've been researching",
        "i looked up how to",
        "i know how to kill myself",
        "i know methods",
        "i've thought about methods",
        "i've been drinking a lot",
        "i've been using drugs",
        "i've been self-medicating",
        "i've written a note",
        "i wrote a letter",
        "i'm giving away my stuff",
        "i'm giving away my possessions",
        "i'm getting my affairs in order",
        "i'm saying my goodbyes",
        "i've been saying goodbye",
        "people will be better off",
        "my family will be better off",
        "my friends will be better off",
        "they'll be happier without me",
        "i'm a burden to everyone",
        "i'm just a burden to my family",
        "i'm a burden to my friends",
        "everyone would be happier",
        "no one cares about me",
        "nobody cares",
        "no one would notice",
        "no one would care",
        "i'm invisible",
        "i don't matter",
        "my life doesn't matter",
        "i have no purpose",
        "my life has no meaning",
        "what's the point of living",
        "why should i keep living",
        "why am i alive",
        "i shouldn't be alive",
        "i don't deserve to live",
        "i deserve to die",
        "death would be a relief",
        "i long for death",
        "i welcome death",
        "i'm not afraid to die",
        "i don't fear death",
        "death doesn't scare me",
        "i'd welcome the peace",
        "i want peace",
        "i want to rest",
        "i want eternal sleep",
        "i'm tired of fighting",
        "i can't fight anymore",
        "i'm exhausted",
        "i'm so tired",
        "i'm drained",
        "i have no energy left",
        "i'm at my breaking point",
        "i'm breaking",
        "i'm falling apart",
        "i'm losing it",
        "i'm losing my mind",
        "i can't hold on",
        "i can't keep going",
        "i don't know how much longer",
        "i don't know if i can make it",
        "i don't see things getting better",
        "things will never get better",
        "it will never get better",
        "nothing will ever change",
        "i'm stuck",
        "i'm in a dark place",
        "i'm drowning",
        "i'm suffocating",
        "i can't breathe",
        "i feel like i'm dying",
        "i'm dying inside",
        "part of me is already dead",
        "i've lost myself",
        "i don't know who i am",
        "i don't recognize myself",
        "i hate myself",
        "i despise myself",
        "i'm disgusting",
        "i'm a failure",
        "i've failed at everything",
        "i ruin everything",
        "i destroy everything",
        "i hurt everyone",
        "i'm toxic",
        "i'm poison",
        "i'm cursed",
        "i'm doomed",
        "my life is ruined",
        "everything is ruined",
        "i've messed up everything",
        "i can't fix this",
        "it's unfixable",
        "i'm beyond help",
        "no one can help me",
        "help won't work",
        "therapy doesn't work",
        "medication doesn't work",
        "nothing works",
        "i've tried everything",
        "nothing helps",
        "i'm unhelpable",
        "i'm a lost cause",
        "i'm damaged beyond repair",
        "i'm broken",
        "i'm shattered",
        "i'm destroyed",
        "i'm defeated",
        "i surrender",
        "i give up on life",
        "i've given up on life",
        "life has given up on me",
        "i've lost the will to live",
        "i have no will to live",
        "i don't have the strength",
        "i'm too weak",
        "i'm not strong enough",
        "i can't handle this",
        "i can't cope",
        "i can't deal with this",
        "it's too much",
        "this is too much",
        "everything is too much",
        "i'm overwhelmed",
        "i'm drowning in",
        "i'm buried under",
        "i'm crushed by",
        "the weight is too heavy",
        "i'm sinking",
        "i'm falling",
        "i'm spiraling",
        "i'm out of control",
        "i've lost control",
        "i can't control anything",
        "my life is out of control",
        "chaos",
        "everything is chaos",
        "my mind is chaos",
        "i can't think straight",
        "my thoughts are racing",
        "i can't stop thinking about",
        "intrusive thoughts",
        "unwanted thoughts",
        "dark thoughts",
        "scary thoughts",
        "frightening thoughts",
        "terrifying thoughts",
        "i'm scared of myself",
        "i don't trust myself",
        "i'm afraid of what i might do",
        "i'm worried about myself",
        "i need help but",
        "i want help but",
        "i should get help but",
        "i know i need help",
        "maybe i should get help",
        "i'm reaching out",
        "i'm asking for help",
        "please help me",
        "someone help me",
        "i don't want to feel this way",
        "i don't want to be here",
        "i don't want to exist",
        "i wish i didn't exist",
        "i wish i could cease to exist",
        "i want to vanish",
        "i want to fade away",
        "i'm disappearing",
        "i'm fading",
        "i'm becoming nothing",
    ]
    
    SELF_HARM_HIGH: List[str] = [
        # Strong self-harm indicators
        "i cut",
        "i've been cutting",
        "i used to cut",
        "i started cutting again",
        "i'm cutting again",
        "relapsed with cutting",
        "i relapsed",
        "i'm relapsing",
        "i want to cut",
        "i feel like cutting",
        "i'm fighting the urge to cut",
        "the urge to cut",
        "urges to self harm",
        "self harm urges",
        "i want to hurt myself",
        "i want to harm myself",
        "i feel like hurting myself",
        "i'm thinking about hurting myself",
        "i've been hurting myself",
        "i've been self harming",
        "i self harm",
        "i do self harm",
        "i practice self harm",
        "i engage in self harm",
        "self injury",
        "i injure myself",
        "i've injured myself",
        "self mutilation",
        "i mutilate myself",
        "i scratch until i bleed",
        "i pick at my skin",
        "i pick my skin",
        "dermatillomania",
        "i pull out my hair",
        "trichotillomania",
        "i hit things",
        "i punch walls",
        "i hurt myself on purpose",
        "i cause myself pain",
        "i inflict pain on myself",
        "i deserve to feel pain",
        "pain is the only thing i feel",
        "pain is all i have",
        "pain reminds me i'm alive",
        "i need to feel pain to feel real",
        "i cut to feel",
        "i cut to cope",
        "cutting helps",
        "self harm helps",
        "it helps me cope",
        "it's my coping mechanism",
        "i don't know how else to cope",
        "i can't cope without it",
        "i can't stop",
        "i can't stop cutting",
        "i can't stop hurting myself",
        "it's an addiction",
        "i'm addicted to",
        "i have scars",
        "my scars",
        "i hide my scars",
        "i'm ashamed of my scars",
        "fresh cuts",
        "new cuts",
        "i have fresh cuts",
        "my cuts are deep",
        "i cut deep",
        "i cut too deep",
        "it's bleeding a lot",
        "i can't stop the bleeding",
        "i need stitches",
        "i should get stitches",
        "i'm worried about infection",
        "my wounds",
        "my cuts are infected",
        "i think it's infected",
        "i burned myself",
        "i've been burning",
        "cigarette burns",
        "i use fire",
        "i use heat",
        "i don't eat",
        "i starve",
        "i restrict food",
        "i skip meals",
        "i count calories obsessively",
        "i'm obsessed with my weight",
        "i hate my body",
        "i'm disgusting",
        "i'm fat and disgusting",
        "i make myself sick",
        "i force myself to vomit",
        "i throw up on purpose",
        "i purge my food",
        "i use laxatives",
        "i take too many laxatives",
        "i exercise too much",
        "i'm obsessed with exercise",
        "i work out excessively",
        "i'm abusing substances",
        "i use drugs to cope",
        "i drink to forget",
        "i get high to escape",
        "substance abuse",
        "i'm using again",
        "i relapsed on drugs",
        "i relapsed on alcohol",
    ]
    
    HOPELESSNESS_HIGH: List[str] = [
        # Strong hopelessness indicators
        "i have no hope",
        "there's no hope",
        "hopeless",
        "i'm hopeless",
        "i feel hopeless",
        "utterly hopeless",
        "completely hopeless",
        "totally hopeless",
        "absolutely hopeless",
        "beyond hope",
        "past hope",
        "no hope left",
        "all hope is lost",
        "i've lost hope",
        "hope is dead",
        "i killed my hope",
        "i have no dreams",
        "my dreams are dead",
        "i've given up on my dreams",
        "my future is bleak",
        "i have no future",
        "there's no future for me",
        "i can't imagine a future",
        "i don't have a future",
        "my life is going nowhere",
        "i'm going nowhere",
        "i'm stuck in life",
        "i'm trapped in life",
        "there's no way forward",
        "i can't move forward",
        "i'm not moving forward",
        "i'm regressing",
        "i'm getting worse",
        "things are getting worse",
        "everything is getting worse",
        "it's all downhill",
        "my life is falling apart",
        "everything is falling apart",
        "my world is crumbling",
        "my world collapsed",
        "i've hit rock bottom",
        "i'm at rock bottom",
        "this is the lowest i've been",
        "i can't get any lower",
        "i've never been this bad",
        "this is the worst i've felt",
        "i've never felt this bad",
        "i feel worse than ever",
        "every day is worse",
        "it's getting harder",
        "everything is harder",
        "i can't do anything right",
        "i fail at everything",
        "everything i touch fails",
        "i'm a failure at life",
        "i've failed at life",
        "my life is a failure",
        "i'm a disappointment",
        "i disappoint everyone",
        "i let everyone down",
        "i always let people down",
        "i ruin relationships",
        "i destroy relationships",
        "i push people away",
        "i drive people away",
        "no one stays with me",
        "everyone leaves me",
        "i'm always alone",
        "i'll always be alone",
        "i'm meant to be alone",
        "i don't deserve love",
        "i don't deserve happiness",
        "i don't deserve good things",
        "good things don't happen to me",
        "nothing good ever happens",
        "bad things always happen to me",
        "i have bad luck",
        "i'm cursed",
        "i'm jinxed",
        "the universe hates me",
        "life hates me",
        "god hates me",
        "i'm being punished",
        "this is my punishment",
        "i deserve this suffering",
        "i deserve to suffer",
        "suffering is all i know",
        "pain is my constant companion",
        "i only know pain",
        "happiness is not for me",
        "i can't be happy",
        "i don't know how to be happy",
        "i've forgotten how to be happy",
        "i don't remember happiness",
        "i can't feel joy",
        "joy is foreign to me",
        "nothing brings me joy",
        "nothing makes me happy",
        "i feel nothing good",
        "all i feel is pain",
        "all i feel is sadness",
        "all i feel is emptiness",
        "i'm empty",
        "i feel empty",
        "i'm hollow inside",
        "i'm a shell",
        "i'm a ghost of myself",
        "i've lost my spark",
        "my light is gone",
        "the light inside me died",
        "i'm in darkness",
        "i'm surrounded by darkness",
        "darkness is all i see",
        "i can't see the light",
        "there's no light at the end",
        "no light at the end of the tunnel",
        "the tunnel has no end",
        "i'm in an endless tunnel",
        "i'm lost",
        "i'm so lost",
        "i can't find my way",
        "i have no direction",
        "i'm wandering aimlessly",
        "i have no purpose",
        "my life has no purpose",
        "i serve no purpose",
        "i'm useless",
        "i have no use",
        "i contribute nothing",
        "i'm a waste of space",
        "i'm wasting oxygen",
        "i shouldn't take up space",
        "the world has no use for me",
        "society doesn't need me",
        "i'm irrelevant",
        "i don't matter to anyone",
        "i'm insignificant",
        "i'm a speck of dust",
        "i'm nothing",
        "i am nothing",
        "i feel like nothing",
        "i'm worthless",
        "i have no value",
        "i'm valueless",
        "my existence is worthless",
        "my life has no value",
    ]
    
    # =========================================================================
    # MODERATE SEVERITY - ELEVATED CONCERN
    # =========================================================================
    
    SUICIDAL_MODERATE: List[str] = [
        # Moderate indicators to monitor
        "sometimes i think about",
        "occasionally i think about",
        "i've wondered about",
        "i wonder what it would be like",
        "what if i wasn't here",
        "what if i disappeared",
        "people might be better off",
        "maybe they'd be better off",
        "i feel like a burden sometimes",
        "i worry i'm a burden",
        "i don't feel useful",
        "i don't feel needed",
        "i feel unnecessary",
        "i feel replaceable",
        "anyone could replace me",
        "i'm easily forgotten",
        "people forget about me",
        "i'm always last",
        "i'm always left out",
        "no one thinks of me",
        "no one considers me",
        "i'm overlooked",
        "i'm ignored",
        "people don't see me",
        "i'm unseen",
        "i feel invisible",
        "i blend into the background",
        "i'm just background noise",
        "i don't stand out",
        "i'm not special",
        "i'm not important",
        "i'm not significant",
        "my problems don't matter",
        "my feelings don't matter",
        "no one cares how i feel",
        "no one asks how i am",
        "people don't check on me",
        "i'm always the one reaching out",
        "i initiate everything",
        "if i stopped trying",
        "if i disappeared",
        "would anyone notice",
        "would anyone care",
        "i doubt anyone would notice",
        "i doubt anyone would care",
        "i feel alone",
        "i'm so alone",
        "i feel lonely",
        "i'm always lonely",
        "loneliness is constant",
        "i'm isolated",
        "i isolate myself",
        "i push people away",
        "i keep people at a distance",
        "i don't let people in",
        "i have walls up",
        "i'm guarded",
        "i can't be vulnerable",
        "i can't open up",
        "i don't know how to connect",
        "i struggle to connect",
        "connections feel fake",
        "relationships feel shallow",
        "no one really knows me",
        "no one understands me",
        "i'm misunderstood",
        "people don't get me",
        "i'm different",
        "i don't fit in",
        "i never fit in",
        "i've never fit in",
        "i'm an outsider",
        "i don't belong anywhere",
        "i have no place",
        "i have no home",
        "i'm drifting",
        "i'm floating",
        "i'm untethered",
        "i have no anchor",
        "i have no foundation",
        "i have no roots",
        "i'm disconnected",
        "i feel disconnected",
        "i'm detached",
        "i feel detached",
        "i'm numb",
        "i feel numb",
        "i can't feel anything",
        "my feelings are dulled",
        "everything is muted",
        "life feels muted",
        "colors are dull",
        "food has no taste",
        "music doesn't move me",
        "nothing moves me",
        "i'm unmoved",
        "i'm unfeeling",
        "i'm cold inside",
        "i'm dead inside",
        "part of me died",
        "something in me died",
        "i've lost my passion",
        "i've lost my drive",
        "i've lost my motivation",
        "i can't get motivated",
        "i have no energy",
        "i'm always tired",
        "fatigue is constant",
        "i'm exhausted all the time",
        "i sleep too much",
        "i can't sleep enough",
        "sleep is my escape",
        "i sleep to escape",
        "i wish i could sleep forever",
        "i'm tired of everything",
        "i'm tired of life",
        "i'm tired of trying",
        "i'm tired of fighting",
        "i'm tired of struggling",
        "the struggle is endless",
        "life is a struggle",
        "everything is a struggle",
        "nothing comes easy",
        "everything is hard",
        "life is hard",
        "life is painful",
        "life is suffering",
        "existence is suffering",
        "being alive hurts",
        "consciousness is painful",
        "awareness is painful",
        "thinking is painful",
        "feeling is painful",
        "i'm sensitive to everything",
        "everything hurts",
        "i'm raw",
        "i'm exposed",
        "i'm vulnerable",
        "i feel fragile",
        "i feel broken",
        "i feel damaged",
        "i feel flawed",
        "i'm defective",
        "something is wrong with me",
        "i'm not right",
        "i'm messed up",
        "i'm screwed up",
        "i'm twisted",
        "i'm warped",
        "i'm not normal",
        "i'll never be normal",
        "i can't be fixed",
        "i'm beyond repair",
        "i'm too damaged",
        "i'm too broken",
        "i'm too far gone",
        "it's too late for me",
        "i missed my chance",
        "opportunities passed me by",
        "life passed me by",
        "i wasted my life",
        "i wasted my potential",
        "i had potential once",
        "i could have been",
        "i used to be",
        "i'm not who i was",
        "i've lost myself",
        "i don't know who i am",
        "i've forgotten who i am",
        "i'm a stranger to myself",
        "i don't recognize my life",
        "this isn't my life",
        "this isn't how it was supposed to be",
        "my life didn't turn out",
        "i'm disappointed in my life",
        "i'm disappointed in myself",
        "i let myself down",
        "i didn't live up to",
        "i didn't meet expectations",
        "i failed expectations",
        "i'm a letdown",
        "i'm a failure",
        "i failed",
        "i keep failing",
        "i always fail",
        "failure is all i know",
        "i expect to fail",
        "i know i'll fail",
        "why bother trying",
        "what's the point of trying",
        "trying is pointless",
        "effort is wasted",
        "nothing i do matters",
        "my actions don't matter",
        "i can't make a difference",
        "i'm powerless",
        "i'm helpless",
        "i have no control",
        "i have no power",
        "i'm at the mercy of",
        "life controls me",
        "circumstances control me",
        "i'm a victim",
        "i'm victimized",
        "life victimizes me",
        "the world is against me",
        "everyone is against me",
        "people are against me",
        "i'm targeted",
        "i'm persecuted",
        "bad things follow me",
        "tragedy follows me",
        "i attract bad luck",
        "i'm a magnet for problems",
        "problems find me",
        "trouble finds me",
        "i can't catch a break",
        "i never catch a break",
        "i have no luck",
        "i'm unlucky",
        "misfortune is my companion",
        "sorrow is my companion",
        "grief is my companion",
        "loss is constant",
        "i've lost so much",
        "i keep losing",
        "i lose everything",
        "i lose everyone",
        "people leave me",
        "people die on me",
        "people abandon me",
        "i'm abandoned",
        "i'm forsaken",
        "i'm rejected",
        "rejection is constant",
        "i'm always rejected",
        "i expect rejection",
        "i anticipate rejection",
        "i'm defensive",
        "i'm guarded",
        "i protect myself",
        "i don't get close",
        "closeness scares me",
        "intimacy scares me",
        "love scares me",
        "happiness scares me",
        "good things scare me",
        "i'm waiting for the other shoe",
        "i'm waiting for bad news",
        "i expect the worst",
        "the worst always happens",
        "my fears come true",
        "my worries are validated",
        "i was right to worry",
        "i knew it would go wrong",
        "i predicted this",
        "i saw this coming",
        "it's always like this",
        "it never changes",
        "nothing changes",
        "i never change",
        "i can't change",
        "change is impossible",
        "i'm stuck in my ways",
        "i'm stuck in patterns",
        "i repeat the same mistakes",
        "i'm in a cycle",
        "i'm in a loop",
        "i'm trapped in a cycle",
        "history repeats",
        "my history repeats",
        "i'm doomed to repeat",
        "i'm my own worst enemy",
        "i sabotage myself",
        "i self-sabotage",
        "i ruin good things",
        "i don't deserve good things",
        "good things feel wrong",
        "happiness feels wrong",
        "joy feels foreign",
        "i'm uncomfortable with happiness",
        "i'm uncomfortable with peace",
        "calm makes me anxious",
        "peace makes me anxious",
        "quiet makes me anxious",
        "i need chaos",
        "chaos feels normal",
        "dysfunction feels normal",
        "pain feels normal",
        "suffering feels normal",
        "this is my normal",
        "this is all i know",
        "i've never known different",
        "i don't know another way",
        "i can't imagine different",
        "different seems impossible",
        "better seems impossible",
        "improvement seems impossible",
        "healing seems impossible",
        "recovery seems impossible",
        "i'll never recover",
        "i'll never heal",
        "i'll always be this way",
        "this is permanent",
        "this is forever",
        "i'll never change",
        "i can't be helped",
        "help won't work for me",
        "i'm beyond helping",
        "i'm a hopeless case",
    ]
    
    SELF_HARM_MODERATE: List[str] = [
        # Moderate self-harm indicators
        "i've thought about cutting",
        "i've considered cutting",
        "i wonder if cutting would help",
        "i've been curious about",
        "i've researched self harm",
        "i've looked up self harm",
        "i know about self harm",
        "i understand why people",
        "i get why people cut",
        "i see the appeal",
        "i understand the appeal",
        "i've been tempted",
        "i've been close to",
        "i almost did it",
        "i came close",
        "i was about to",
        "i stopped myself",
        "i resisted",
        "i fought the urge",
        "the urge was strong",
        "i had a strong urge",
        "urges are getting stronger",
        "urges are more frequent",
        "urges are harder to resist",
        "it's getting harder to resist",
        "resistance is exhausting",
        "fighting urges is tiring",
        "i'm tired of fighting urges",
        "i'm running out of strength",
        "my willpower is fading",
        "i don't know how much longer i can resist",
        "i don't know if i can keep resisting",
        "resistance feels futile",
        "fighting feels futile",
        "why am i fighting",
        "what's the point of resisting",
        "resistance is pointless",
        "i'm going to give in",
        "i'll probably give in",
        "i know i'll give in",
        "it's just a matter of time",
        "i can feel myself slipping",
        "i'm slipping",
        "i'm losing ground",
        "i'm losing the battle",
        "the battle is lost",
        "i've lost the fight",
        "i stopped fighting",
        "i gave up fighting",
        "i surrendered",
        "i submitted",
        "i let go",
        "i released control",
        "i stopped caring",
        "i don't care anymore",
        "caring is too hard",
        "caring is exhausting",
        "i'm too tired to care",
        "apathy is easier",
        "numbness is easier",
        "pain is familiar",
        "pain is comfortable",
        "pain is my friend",
        "pain understands me",
        "pain doesn't lie",
        "pain is honest",
        "pain is real",
        "at least pain is real",
        "at least i can feel pain",
        "pain proves i'm alive",
        "pain proves i exist",
        "pain validates me",
        "pain makes me feel something",
        "something is better than nothing",
        "pain is better than emptiness",
        "pain is better than numbness",
        "i'd rather feel pain",
        "i prefer pain",
        "i'm drawn to pain",
        "i'm attracted to pain",
        "pain calls to me",
        "i think about pain",
        "i fantasize about",
        "i imagine hurting myself",
        "i visualize",
        "i picture myself",
        "scenarios play in my mind",
        "intrusive images",
        "unwanted images",
        "disturbing thoughts",
        "disturbing images",
        "dark fantasies",
        "i'm ashamed of my thoughts",
        "i'm scared of my thoughts",
        "my thoughts scare me",
        "i don't like my thoughts",
        "i try to stop thinking",
        "i can't stop thinking",
        "thoughts won't leave",
        "thoughts are persistent",
        "thoughts are intrusive",
        "thoughts are obsessive",
        "i'm obsessed with",
        "i'm preoccupied with",
        "i can't stop thinking about pain",
        "i can't stop thinking about blood",
        "i can't stop thinking about scars",
        "i look at my scars",
        "i touch my scars",
        "scars are comforting",
        "scars remind me",
        "scars tell my story",
        "scars are my history",
        "scars are proof",
        "proof of my pain",
        "proof i survived",
        "proof i exist",
        "i'm proud of my scars",
        "i'm ashamed of my scars",
        "mixed feelings about scars",
        "scars are complicated",
        "my relationship with scars",
        "i hide my scars",
        "i cover my scars",
        "long sleeves always",
        "i never show my arms",
        "i never show my legs",
        "i'm careful about clothing",
        "i plan outfits around scars",
        "i'm self-conscious about scars",
        "i worry people will see",
        "i worry people will notice",
        "i worry people will ask",
        "i don't want questions",
        "i don't want to explain",
        "explanation is too hard",
        "explanation is painful",
        "i lie about scars",
        "i make excuses",
        "i blame accidents",
        "i blame animals",
        "i blame everything else",
        "i can't admit the truth",
        "truth is too shameful",
        "shame is overwhelming",
        "guilt is overwhelming",
        "i feel guilty",
        "i feel ashamed",
        "shame consumes me",
        "guilt consumes me",
        "i'm consumed by",
        "i'm overwhelmed by",
        "emotions are overwhelming",
        "feelings are too much",
        "i can't handle emotions",
        "emotions drown me",
        "i'm drowning in feelings",
        "feelings flood me",
        "i'm flooded",
        "i'm overwhelmed",
        "overwhelm is constant",
        "i can't cope with feelings",
        "i don't know how to cope",
        "i need coping mechanisms",
        "i need healthier coping",
        "i want healthier coping",
        "i'm trying to find alternatives",
        "i'm exploring alternatives",
        "alternatives don't work",
        "nothing works as well",
        "nothing is as effective",
        "self harm is effective",
        "self harm works",
        "it works for me",
        "it helps me function",
        "it gets me through",
        "it keeps me going",
        "i rely on it",
        "i depend on it",
        "i need it",
        "i can't function without it",
        "i'm dependent",
        "i'm addicted",
        "addiction is real",
        "this is addiction",
        "i recognize the addiction",
        "i want to stop",
        "i've tried to stop",
        "i've attempted to quit",
        "quitting is hard",
        "stopping is hard",
        "relapse happens",
        "i've relapsed before",
        "i'll probably relapse",
        "relapse is part of recovery",
        "recovery is not linear",
        "i know recovery is possible",
        "i've seen people recover",
        "i want to recover",
        "i'm not ready to recover",
        "i'm scared to recover",
        "recovery is scary",
        "life without self harm",
        "i can't imagine stopping",
        "stopping feels impossible",
        "quitting feels impossible",
        "i'm not strong enough to quit",
        "i don't have the strength",
        "i need more strength",
        "i need support",
        "i need help",
        "i want help",
        "i'm asking for help",
        "i'm reaching out",
        "i'm trying to reach out",
        "reaching out is hard",
        "asking for help is hard",
        "i'm afraid to ask",
        "i'm ashamed to ask",
        "i don't want to burden",
        "i don't want to bother",
        "people have their own problems",
        "people don't want to hear",
        "no one wants to know",
        "no one wants to help",
        "i'm on my own",
        "i have to handle this alone",
        "alone is how i handle things",
        "isolation is my pattern",
        "i isolate when struggling",
        "i withdraw when hurting",
        "i hide my pain",
        "i hide my struggles",
        "i put on a mask",
        "i pretend i'm fine",
        "i fake being okay",
        "no one knows",
        "no one suspects",
        "i'm good at hiding",
        "i've gotten good at hiding",
        "hiding is exhausting",
        "pretending is exhausting",
        "the mask is heavy",
        "i want to drop the mask",
        "i want to be real",
        "i want to be honest",
        "honesty is scary",
        "vulnerability is scary",
        "i'm scared to be vulnerable",
        "i'm scared to open up",
        "opening up feels dangerous",
        "being seen feels dangerous",
        "being known feels dangerous",
        "i protect myself",
        "protection is necessary",
        "i've been hurt before",
        "i've been betrayed",
        "trust is hard",
        "i don't trust easily",
        "i'm cautious",
        "i'm guarded for a reason",
        "my guard is up",
        "walls keep me safe",
        "walls also keep me lonely",
        "loneliness is the price",
        "isolation is the price",
        "i pay the price",
        "i accept the loneliness",
        "i've accepted my fate",
        "this is my life",
        "this is how it is",
        "i've made peace with",
        "i've resigned myself",
        "resignation",
        "acceptance of pain",
        "pain is my companion",
        "i walk with pain",
        "i carry pain",
        "pain is my burden",
        "i bear the burden",
        "i endure",
        "endurance is my strength",
        "survival is my achievement",
        "i'm still here",
        "i'm surviving",
        "survival is all i can do",
        "survival is enough",
        "survival is success",
        "i'm a survivor",
        "i've survived",
        "i'll keep surviving",
        "one day at a time",
        "one moment at a time",
        "one breath at a time",
        "i keep breathing",
        "breathing is enough",
        "existing is enough",
        "i exist",
        "existence is resistance",
        "staying alive is resistance",
        "i resist by staying alive",
        "i fight by existing",
        "my existence is defiance",
        "defiance keeps me going",
        "anger keeps me going",
        "spite keeps me going",
        "i stay alive out of spite",
        "i refuse to give up",
        "i refuse to surrender",
        "not yet",
        "not today",
        "today i survive",
        "today i endure",
        "today i exist",
        "tomorrow is another day",
        "tomorrow might be better",
        "hope for tomorrow",
        "i hope for better",
        "i hope for change",
        "i hope for healing",
        "hope is small",
        "hope is faint",
        "hope is there",
        "i hold onto hope",
        "i cling to hope",
        "hope keeps me here",
        "hope is my anchor",
        "i'm anchored by hope",
        "i'm anchored by something",
        "something keeps me here",
        "something keeps me going",
        "i don't know what",
        "i don't understand why",
        "but i'm still here",
        "i'm still here",
        "i'm still fighting",
        "i'm still trying",
        "i haven't given up",
        "not completely",
        "not entirely",
        "part of me holds on",
        "part of me wants to live",
        "part of me wants better",
        "there's a part that hopes",
        "there's a part that dreams",
        "dreams still exist",
        "dreams are buried",
        "dreams are dormant",
        "dreams can wake",
        "i can dream again",
        "i will dream again",
        "someday i'll dream",
        "someday i'll hope",
        "someday i'll heal",
        "someday i'll be okay",
        "okay is possible",
        "okay is achievable",
        "i believe in okay",
        "i believe in better",
        "belief is hard",
        "belief requires faith",
        "faith is hard",
        "i'm working on faith",
        "i'm working on belief",
        "i'm working on hope",
        "work in progress",
        "i'm a work in progress",
        "progress is slow",
        "progress is messy",
        "progress is non-linear",
        "but there is progress",
        "i see progress",
        "i acknowledge progress",
        "i celebrate small wins",
        "small wins matter",
        "small steps matter",
        "every step counts",
        "i'm moving forward",
        "slowly but surely",
        "i'm on a journey",
        "healing is a journey",
        "recovery is a journey",
        "i'm on the path",
        "i'm finding my way",
        "i'm finding myself",
        "i'm rediscovering myself",
        "i'm learning who i am",
        "i'm learning to live",
        "i'm learning to cope",
        "i'm learning to feel",
        "i'm learning to be",
        "learning is ongoing",
        "growth is ongoing",
        "i'm growing",
        "i'm changing",
        "change is possible",
        "i am possible",
        "my healing is possible",
        "my recovery is possible",
        "my future is possible",
        "possibility exists",
        "i exist in possibility",
        "i choose possibility",
        "i choose hope",
        "i choose life",
        "i choose to stay",
        "i choose to fight",
        "i choose to heal",
        "i choose to grow",
        "i choose to believe",
        "i choose to try",
        "i choose to continue",
        "i choose to exist",
        "my choice matters",
        "my choices matter",
        "i have agency",
        "i have power",
        "i have strength",
        "strength is within me",
        "strength is growing",
        "i am strong",
        "i am resilient",
        "i am capable",
        "i am worthy",
        "i deserve good things",
        "i deserve healing",
        "i deserve happiness",
        "i deserve peace",
        "i deserve love",
        "i am deserving",
        "i am enough",
        "i am whole",
        "i am healing",
        "i am recovering",
        "i am becoming",
        "i am becoming whole",
        "i am becoming me",
        "the real me",
        "the true me",
        "me without pain",
        "me without shame",
        "me without fear",
        "me without self harm",
        "that me is possible",
        "that me is coming",
        "i'm becoming that me",
        "i'm on my way",
        "i'm getting there",
        "i'll get there",
        "i believe i'll get there",
        "i have faith i'll get there",
        "i trust the process",
        "i trust myself",
        "i trust my journey",
        "journey continues",
        "i continue",
        "i persist",
        "i persevere",
        "i am persistent",
        "i am perseverance",
        "i am resilience",
        "i am hope",
    ]
    
    HOPELESSNESS_MODERATE: List[str] = [
        # Moderate hopelessness indicators
        "i'm discouraged",
        "i feel discouraged",
        "discouragement",
        "i'm disheartened",
        "i feel disheartened",
        "i'm demoralized",
        "i feel demoralized",
        "i'm down",
        "i feel down",
        "feeling down",
        "i'm low",
        "i feel low",
        "low mood",
        "i'm in a slump",
        "i'm in a funk",
        "i'm stuck in a rut",
        "i'm in a rough patch",
        "going through a rough patch",
        "it's been tough",
        "things have been hard",
        "life has been hard",
        "recently has been difficult",
        "lately has been challenging",
        "i'm struggling lately",
        "i've been struggling",
        "struggling with",
        "having a hard time",
        "going through something",
        "dealing with something",
        "processing something",
        "working through something",
        "trying to work through",
        "trying to process",
        "trying to cope",
        "coping is difficult",
        "coping is a challenge",
        "i'm challenged",
        "i'm being tested",
        "life is testing me",
        "this is a test",
        "i'm being pushed",
        "i'm at my limit",
        "i'm near my limit",
        "i'm reaching my limit",
        "my capacity is full",
        "i have no bandwidth",
        "i have no capacity",
        "i'm maxed out",
        "i'm burned out",
        "burnout is real",
        "i'm experiencing burnout",
        "i'm depleted",
        "i'm drained",
        "i'm empty",
        "i need to recharge",
        "i need rest",
        "i need a break",
        "i need time",
        "i need space",
        "i need support",
        "i need help",
        "i'm asking for support",
        "i'm seeking help",
        "i'm reaching out",
        "i'm trying to get help",
        "help is hard to find",
        "support is hard to find",
        "resources are limited",
        "i don't know where to turn",
        "i don't know what to do",
        "i'm at a loss",
        "i'm confused",
        "i'm uncertain",
        "i'm unsure",
        "i have doubts",
        "i'm doubtful",
        "i'm skeptical",
        "i'm pessimistic",
        "i tend to be pessimistic",
        "i expect the worst",
        "i prepare for the worst",
        "i'm cautious about optimism",
        "optimism feels naive",
        "hope feels risky",
        "i'm afraid to hope",
        "i'm afraid to expect good",
        "disappointment hurts",
        "i've been disappointed",
        "i've been let down",
        "i don't want to be let down",
        "i protect myself from disappointment",
        "i lower my expectations",
        "i keep expectations low",
        "low expectations are safer",
        "i don't get my hopes up",
        "i try not to hope",
        "i try not to expect",
        "expectations lead to pain",
        "hope leads to pain",
        "i've learned not to hope",
        "i've learned to expect less",
        "adaptation to disappointment",
        "i've adapted to low expectations",
        "this is my adaptation",
        "survival mechanism",
        "low expectations are survival",
        "pessimism is protection",
        "cynicism is protection",
        "i'm cynical",
        "i tend toward cynicism",
        "i see the negative",
        "i focus on the negative",
        "negativity bias",
        "i have a negativity bias",
        "i notice problems",
        "i notice what's wrong",
        "i'm critical",
        "i'm self-critical",
        "i criticize myself",
        "my inner critic",
        "the voice in my head",
        "negative self-talk",
        "i talk negatively to myself",
        "i'm hard on myself",
        "i'm my own critic",
        "i judge myself harshly",
        "harsh self-judgment",
        "i'm never good enough",
        "nothing i do is good enough",
        "i set high standards",
        "i have high expectations of myself",
        "perfectionism",
        "i'm a perfectionist",
        "perfectionism is exhausting",
        "i can't meet my own standards",
        "i fail my own standards",
        "i disappoint myself",
        "i let myself down",
        "i'm failing myself",
        "i'm not living up to",
        "i'm not achieving",
        "i'm not progressing",
        "i'm stagnant",
        "i feel stagnant",
        "stagnation",
        "i'm not growing",
        "i want to grow",
        "i want to improve",
        "improvement feels slow",
        "growth feels slow",
        "progress feels slow",
        "i'm impatient",
        "i want results now",
        "i want to feel better now",
        "healing takes time",
        "i know healing takes time",
        "time is hard",
        "waiting is hard",
        "patience is hard",
        "i'm not patient",
        "i struggle with patience",
        "i want immediate relief",
        "relief feels distant",
        "better feels distant",
        "improvement feels distant",
        "the future feels far",
        "i can't see ahead",
        "i can't see the path",
        "the path is unclear",
        "direction is unclear",
        "i'm directionless",
        "i need direction",
        "i need guidance",
        "i'm seeking guidance",
        "i'm looking for answers",
        "answers are elusive",
        "clarity is elusive",
        "i'm confused about",
        "i'm uncertain about",
        "i don't know what i want",
        "i don't know who i am",
        "identity is confusing",
        "i'm questioning myself",
        "i'm questioning my path",
        "i'm questioning my choices",
        "regret about choices",
        "i have regrets",
        "i regret decisions",
        "i wish i'd chosen differently",
        "hindsight is painful",
        "if only",
        "what if i had",
        "what if i'd",
        "alternate realities",
        "i imagine different paths",
        "different choices",
        "different outcomes",
        "parallel lives",
        "i wonder what could have been",
        "the road not taken",
        "i took the wrong road",
        "i'm on the wrong path",
        "this isn't my path",
        "i need to find my path",
        "searching for purpose",
        "searching for meaning",
        "meaning is elusive",
        "purpose is elusive",
        "i'm searching",
        "i'm seeking",
        "i'm looking for",
        "i'm trying to find",
        "finding is hard",
        "discovery is hard",
        "the search continues",
        "i haven't found",
        "i'm still looking",
        "i keep searching",
        "searching is tiring",
        "seeking is exhausting",
        "i'm tired of searching",
        "i'm tired of seeking",
        "i want to find",
        "i want to discover",
        "i want to know",
        "knowledge is power",
        "understanding helps",
        "i'm trying to understand",
        "i'm trying to make sense",
        "making sense is hard",
        "life doesn't make sense",
        "things don't make sense",
        "i'm confused by life",
        "i'm confused by events",
        "events are bewildering",
        "life is bewildering",
        "i'm bewildered",
        "i'm perplexed",
        "i'm puzzled",
        "i'm trying to piece together",
        "the pieces don't fit",
        "nothing fits together",
        "life feels fragmented",
        "i feel fragmented",
        "i'm in pieces",
        "i'm broken apart",
        "i need to put myself together",
        "integration is needed",
        "wholeness is the goal",
        "i'm working toward wholeness",
        "i'm working toward integration",
        "healing is integration",
        "recovery is integration",
        "i'm on a healing journey",
        "i'm on a recovery path",
        "the journey is long",
        "the path is long",
        "i'm walking the path",
        "i'm continuing the journey",
        "step by step",
        "day by day",
        "moment by moment",
        "i'm present",
        "i'm trying to be present",
        "presence is hard",
        "i'm often elsewhere",
        "my mind wanders",
        "i'm distracted",
        "distraction is common",
        "i escape into",
        "escapism",
        "i use distraction",
        "distraction helps",
        "distraction is coping",
        "coping through distraction",
        "i need healthy distractions",
        "i'm finding healthy outlets",
        "outlets are important",
        "expression is important",
        "i need to express",
        "i'm learning to express",
        "expression is healing",
        "i'm expressing myself",
        "i'm sharing my story",
        "storytelling is healing",
        "i'm telling my story",
        "my story matters",
        "my voice matters",
        "i have a voice",
        "i'm finding my voice",
        "i'm using my voice",
        "speaking up",
        "i'm speaking up",
        "i'm speaking out",
        "advocacy",
        "i'm advocating for myself",
        "self-advocacy",
        "i matter",
        "my experience matters",
        "my feelings matter",
        "my thoughts matter",
        "i am valid",
        "my experience is valid",
        "validation is important",
        "i'm seeking validation",
        "i'm giving myself validation",
        "self-validation",
        "i validate myself",
        "i accept myself",
        "self-acceptance",
        "i'm working on acceptance",
        "acceptance is a process",
        "i accept my journey",
        "i accept my path",
        "i accept where i am",
        "i accept who i am",
        "acceptance brings peace",
        "i'm finding peace",
        "peace is possible",
        "peace is within reach",
        "i can be at peace",
        "i will be at peace",
        "peace is coming",
        "i believe in peace",
    ]
    
    # =========================================================================
    # LOW SEVERITY - MONITOR AND TRACK
    # =========================================================================
    
    GENERAL_CONCERN_LOW: List[str] = [
        # General emotional distress indicators
        "i'm sad",
        "i feel sad",
        "feeling sad",
        "i'm unhappy",
        "i feel unhappy",
        "i'm upset",
        "i feel upset",
        "i'm bothered",
        "something is bothering me",
        "i'm worried",
        "i feel worried",
        "i'm anxious",
        "i feel anxious",
        "i'm nervous",
        "i feel nervous",
        "i'm stressed",
        "i feel stressed",
        "i'm overwhelmed",
        "i feel overwhelmed",
        "i'm tired",
        "i feel tired",
        "i'm exhausted",
        "i feel exhausted",
        "i'm drained",
        "i feel drained",
        "i'm not myself",
        "i don't feel like myself",
        "i'm off",
        "something feels off",
        "i'm not doing well",
        "i'm not okay",
        "i'm struggling",
        "i'm having a hard time",
        "it's been difficult",
        "things are hard",
        "life is challenging",
        "i'm going through something",
        "i'm dealing with something",
        "i need to talk",
        "i need someone to talk to",
        "i need support",
        "i could use support",
        "i'm reaching out",
        "i'm trying to reach out",
        "i want to connect",
        "i need connection",
        "i feel disconnected",
        "i feel lonely",
        "i'm lonely",
        "i feel isolated",
        "i'm isolated",
        "i feel alone",
        "i'm alone",
    ]
    
    def __init__(self):
        """Initialize keyword detection with compiled patterns."""
        self._compile_patterns()
    
    def _compile_patterns(self):
        """Compile regex patterns for efficient matching."""
        # Create severity-grouped keyword lists
        self.all_critical = (
            self.SUICIDAL_CRITICAL + 
            self.SELF_HARM_CRITICAL
        )
        
        self.all_high = (
            self.SUICIDAL_HIGH + 
            self.SELF_HARM_HIGH + 
            self.HOPELESSNESS_HIGH
        )
        
        self.all_moderate = (
            self.SUICIDAL_MODERATE + 
            self.SELF_HARM_MODERATE + 
            self.HOPELESSNESS_MODERATE
        )
        
        self.all_low = self.GENERAL_CONCERN_LOW
        
        # Compile regex patterns for each severity
        self.patterns = {
            KeywordSeverity.CRITICAL: self._compile_keyword_list(self.all_critical),
            KeywordSeverity.HIGH: self._compile_keyword_list(self.all_high),
            KeywordSeverity.MODERATE: self._compile_keyword_list(self.all_moderate),
            KeywordSeverity.LOW: self._compile_keyword_list(self.all_low),
        }
        
        # Category-specific patterns
        self.category_patterns = {
            "suicidal": self._compile_keyword_list(
                self.SUICIDAL_CRITICAL + self.SUICIDAL_HIGH + self.SUICIDAL_MODERATE
            ),
            "self_harm": self._compile_keyword_list(
                self.SELF_HARM_CRITICAL + self.SELF_HARM_HIGH + self.SELF_HARM_MODERATE
            ),
            "hopelessness": self._compile_keyword_list(
                self.HOPELESSNESS_HIGH + self.HOPELESSNESS_MODERATE
            ),
        }
    
    def _compile_keyword_list(self, keywords: List[str]) -> re.Pattern:
        """Compile a list of keywords into an efficient regex pattern."""
        # Escape special characters and create word boundary patterns
        escaped = [re.escape(kw) for kw in keywords]
        # Create pattern that matches whole phrases with word boundaries
        pattern = r'(?:' + '|'.join(escaped) + r')'
        return re.compile(pattern, re.IGNORECASE)
    
    def detect_keywords(self, text: str) -> List[KeywordMatch]:
        """
        Detect crisis keywords in text.
        
        Args:
            text: The text to analyze
            
        Returns:
            List of KeywordMatch objects for all detected keywords
        """
        matches = []
        text_lower = text.lower()
        
        # Check each severity level
        for severity, pattern in self.patterns.items():
            for match in pattern.finditer(text_lower):
                # Get context (50 chars before and after)
                start = max(0, match.start() - 50)
                end = min(len(text), match.end() + 50)
                context = text[start:end]
                
                matches.append(KeywordMatch(
                    keyword=match.group(),
                    severity=severity,
                    category=self._categorize_match(match.group()),
                    position=match.start(),
                    context=context
                ))
        
        # Sort by severity (critical first) then position
        severity_order = {
            KeywordSeverity.CRITICAL: 0,
            KeywordSeverity.HIGH: 1,
            KeywordSeverity.MODERATE: 2,
            KeywordSeverity.LOW: 3
        }
        matches.sort(key=lambda m: (severity_order[m.severity], m.position))
        
        return matches
    
    def _categorize_match(self, keyword: str) -> str:
        """Determine the category of a matched keyword."""
        keyword_lower = keyword.lower()
        
        if any(kw in keyword_lower for kw in self.SUICIDAL_CRITICAL + self.SUICIDAL_HIGH + self.SUICIDAL_MODERATE):
            return "suicidal_ideation"
        elif any(kw in keyword_lower for kw in self.SELF_HARM_CRITICAL + self.SELF_HARM_HIGH + self.SELF_HARM_MODERATE):
            return "self_harm"
        elif any(kw in keyword_lower for kw in self.HOPELESSNESS_HIGH + self.HOPELESSNESS_MODERATE):
            return "hopelessness"
        else:
            return "general_distress"
    
    def get_highest_severity(self, matches: List[KeywordMatch]) -> KeywordSeverity:
        """Get the highest severity from a list of matches."""
        if not matches:
            return None
        
        severity_order = {
            KeywordSeverity.CRITICAL: 3,
            KeywordSeverity.HIGH: 2,
            KeywordSeverity.MODERATE: 1,
            KeywordSeverity.LOW: 0
        }
        
        return max(matches, key=lambda m: severity_order[m.severity]).severity
    
    def has_critical_keywords(self, text: str) -> bool:
        """Quick check for critical keywords."""
        return bool(self.patterns[KeywordSeverity.CRITICAL].search(text.lower()))
    
    def has_any_crisis_keywords(self, text: str) -> bool:
        """Quick check for any crisis keywords."""
        text_lower = text.lower()
        for pattern in self.patterns.values():
            if pattern.search(text_lower):
                return True
        return False


# =============================================================================
# SINGLETON INSTANCE
# =============================================================================

crisis_keywords = CrisisKeywords()
