/**
 * MindMate AI - Analytics Service Types
 * Production-ready TypeScript interfaces and type definitions
 */

// ============================================================================
// Mood & Emotion Types
// ============================================================================

export type MoodLevel = 1 | 2 | 3 | 4 | 5;

export interface MoodEntry {
  id: string;
  userId: string;
  timestamp: Date;
  moodLevel: MoodLevel;
  emotions: Emotion[];
  notes?: string;
  context?: MoodContext;
}

export interface Emotion {
  name: string;
  intensity: number; // 0-1 scale
  category: EmotionCategory;
}

export type EmotionCategory = 
  | 'positive' 
  | 'negative' 
  | 'neutral' 
  | 'anxious' 
  | 'energetic' 
  | 'calm';

export interface MoodContext {
  location?: string;
  activity?: string;
  socialContext?: string;
  weather?: string;
  sleepQuality?: number;
  energyLevel?: number;
}

// ============================================================================
// Task Types
// ============================================================================

export interface Task {
  id: string;
  userId: string;
  title: string;
  description?: string;
  createdAt: Date;
  dueDate?: Date;
  completedAt?: Date;
  status: TaskStatus;
  priority: TaskPriority;
  category?: string;
  tags?: string[];
  estimatedDuration?: number; // in minutes
  actualDuration?: number;
}

export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'cancelled' | 'overdue';
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';

// ============================================================================
// Trigger Types
// ============================================================================

export interface TriggerEvent {
  id: string;
  userId: string;
  timestamp: Date;
  triggerType: TriggerType;
  description: string;
  severity: number; // 1-10
  moodImpact: number; // -5 to +5
  context?: string;
  resolvedAt?: Date;
  copingStrategiesUsed?: string[];
}

export type TriggerType =
  | 'social'
  | 'work'
  | 'family'
  | 'health'
  | 'financial'
  | 'environmental'
  | 'internal'
  | 'unknown';

export interface TriggerPattern {
  triggerType: TriggerType;
  frequency: number;
  averageSeverity: number;
  averageMoodImpact: number;
  commonContexts: string[];
  timeOfDayPattern?: TimePattern;
  dayOfWeekPattern?: Record<string, number>;
  correlationWithMood: number;
}

export interface TimePattern {
  morning: number;
  afternoon: number;
  evening: number;
  night: number;
}

// ============================================================================
// Trend Analysis Types
// ============================================================================

export interface TrendResult {
  direction: TrendDirection;
  strength: number; // 0-1
  confidence: number; // 0-1
  slope: number;
  intercept: number;
  dataPoints: number;
  startValue: number;
  endValue: number;
  changePercent: number;
}

export type TrendDirection = 'improving' | 'declining' | 'stable' | 'volatile';

export interface RollingAverage {
  window: number;
  values: { timestamp: Date; value: number }[];
  current: number;
}

// ============================================================================
// Report Types
// ============================================================================

export interface WeeklyReport {
  userId: string;
  weekStart: Date;
  weekEnd: Date;
  generatedAt: Date;
  summary: ReportSummary;
  moodAnalysis: MoodAnalysis;
  taskAnalysis: TaskAnalysis;
  triggerAnalysis: TriggerAnalysis;
  progressMetrics: ProgressMetrics;
  insights: string[];
  recommendations: Recommendation[];
  narrative: string; // Generated by Claude
}

export interface ReportSummary {
  overallMood: string;
  keyHighlights: string[];
  areasOfConcern: string[];
  wins: string[];
}

export interface MoodAnalysis {
  averageMood: number;
  moodTrend: TrendResult;
  moodVolatility: number;
  dominantEmotions: string[];
  bestDay: { day: string; averageMood: number };
  challengingDay: { day: string; averageMood: number };
}

export interface TaskAnalysis {
  completionRate: number;
  tasksCompleted: number;
  tasksCreated: number;
  overdueTasks: number;
  averageCompletionTime: number;
  productivityTrend: TrendDirection;
}

export interface TriggerAnalysis {
  totalTriggers: number;
  topTriggers: TriggerPattern[];
  triggerFrequencyChange: number;
  mostChallengingContext: string;
}

export interface ProgressMetrics {
  wellnessScore: number;
  scoreChange: number;
  streakDays: number;
  consistencyScore: number;
}

export interface Recommendation {
  category: string;
  title: string;
  description: string;
  priority: 'high' | 'medium' | 'low';
  actionItems?: string[];
}

// ============================================================================
// Progress Score Types
// ============================================================================

export interface ProgressScore {
  userId: string;
  calculatedAt: Date;
  overallScore: number; // 0-100
  componentScores: ComponentScores;
  historicalComparison?: HistoricalComparison;
  percentileRank?: number;
}

export interface ComponentScores {
  moodStability: number; // 0-100
  emotionalAwareness: number;
  taskManagement: number;
  triggerManagement: number;
  consistency: number;
  improvement: number;
}

export interface HistoricalComparison {
  previousScore: number;
  change: number;
  changePercent: number;
  trend: TrendDirection;
}

// ============================================================================
// Milestone Types
// ============================================================================

export interface Milestone {
  id: string;
  userId: string;
  type: MilestoneType;
  title: string;
  description: string;
  achievedAt: Date;
  criteria: MilestoneCriteria;
  reward?: MilestoneReward;
  shared: boolean;
}

export type MilestoneType =
  | 'streak'
  | 'improvement'
  | 'consistency'
  | 'awareness'
  | 'resilience'
  | 'mastery'
  | 'engagement'
  | 'custom';

export interface MilestoneCriteria {
  metric: string;
  threshold: number;
  timeWindow?: number; // days
}

export interface MilestoneReward {
  badgeUrl?: string;
  badgeName: string;
  message: string;
  celebrationType: CelebrationType;
}

export type CelebrationType = 'simple' | 'moderate' | 'major' | 'epic';

export interface MilestoneCheckResult {
  newMilestones: Milestone[];
  updatedMilestones: Milestone[];
  celebrationQueue: CelebrationEvent[];
}

export interface CelebrationEvent {
  milestone: Milestone;
  animationType: string;
  message: string;
  shareable: boolean;
}

// ============================================================================
// Analytics Configuration Types
// ============================================================================

export interface AnalyticsConfig {
  moodWindowSize: number;
  trendConfidenceThreshold: number;
  volatilityThreshold: number;
  progressScoreWeights: ProgressScoreWeights;
  milestoneDefinitions: MilestoneDefinition[];
  reportGenerationDay: number; // 0-6 (Sunday-Saturday)
}

export interface ProgressScoreWeights {
  moodStability: number;
  emotionalAwareness: number;
  taskManagement: number;
  triggerManagement: number;
  consistency: number;
  improvement: number;
}

export interface MilestoneDefinition {
  type: MilestoneType;
  name: string;
  description: string;
  criteria: MilestoneCriteria;
  reward: MilestoneReward;
}

// ============================================================================
// API Response Types
// ============================================================================

export interface AnalyticsResult<T> {
  success: boolean;
  data?: T;
  error?: AnalyticsError;
  metadata: {
    timestamp: Date;
    processingTime: number;
    dataPoints: number;
  };
}

export interface AnalyticsError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}
